### ISSUE TITLE
for without content followed by and bugs

### ISSUE THREAD

**Issue by jeffreylanters** [jeffreylanters/strcss#7]
For will not be opened when it is follow by an and

```perl
for test
and hover
    color grey
```

outputs
```css
._u6jb0x1180txvvc23609335i3540_ /* test */  }
._u6jb0x1180txvvc23609335i3540_:hover { {
	color: grey; }
```
